### ISSUE TITLE
No utility classes were detected in your source files

### ISSUE THREAD

**Issue by kstulgys** [TrellisCommerce/bigcommerce-cornerstone-tailwind-starter-base#8]
### Expected behavior
updated tailwind.sass file with detected utility classess
### Actual behavior
does not update tailwind.sass file with newly added utility classess
### Steps to reproduce behavior
stencil start
npm run tailwind

add tailwind utility class to any component

**Comment by travish** [comment]
Hey @kstulgys, thanks for submitting a report. I'm having issues replicating your findings. Can you be more specific and detailed with your steps to reproduce?

Checking out a fresh copy of our `main` branch yielded a successful result for me. Here is what I did.

1. Run `npm run tailwind`
2. Add `tw-w-full` in a component in the `templates/components/account/add-wishlist.html` file.

Tailwind compiled my changes correctly at the bottom of the `assets/scss/tailwind.scss` file.

**Comment by kstulgys** [comment]
@travish Thank you for the response. It was my mistake. I had `theme: {}` where it should be at least `theme: { extend: {} }` in `tailwind.config.js`. Although when I run `stencil start` I get an error:

```
Error: Function rgb is missing argument $green.
    at options.error (/Users/karolis/.volta/tools/image/packages/@bigcommerce/stencil-cli/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-sass/lib/index.js:290:33) {
  status: 1,
  file: 'tailwind.scss',
  line: 666,
  column: 21,
  formatted: 'Error: Function rgb is missing argument $green.\n' +
    '        on line 84 of stdin\n' +
    '>>   background-color: rgb(168 85 247 / var(--tw-bg-opacity));\n' +
    '\n' +
    '   --------------------^\n'
}
```

Do you have any insights?

**Comment by travish** [comment]
All good! Thanks for reporting back!

Edit: Open a new issue with your other report, I can take a look.
